coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2
    patch:
      default:
        target: auto
        threshold: 2
comment:
  layout: reach, diff, flags, files
  require_changes: false
  behavior: default
codecov:
  require_ci_to_pass: false
  strict_yaml_branch: main
